spring:
  application:
    name: MySpringBootApplication
  datasource:
    url: jdbc:postgresql://localhost:5432/data_jpa
    username: postgres
    password: spi
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
  h2:
    console:
      enabled: true
server:
  port: 8082